version: '3.8'

services:
  # MongoDB database
  mongo:
    image: mongo:latest
    container_name: image_processing_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=image_processing_db
    networks:
      - app_network

  # Python API service
  api:
    build: .
    container_name: image_processing_api
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - DATABASE_NAME=image_processing_db
      - COLLECTION_NAME=image_results
    networks:
      - app_network
    restart: unless-stopped

volumes:
  mongo_data:

networks:
  app_network:
    driver: bridge