name: Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libglib2.0-0 libgomp1

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black flake8 isort

    - name: Run code formatting check
      run: |
        black --check --diff app/ tests/

    - name: Run import sorting check
      run: |
        isort --check-only --diff app/ tests/

    - name: Run linting
      run: |
        flake8 app/ tests/ --max-line-length=100 --ignore=E203,W503

    - name: Run tests
      run: |
        python -m pytest tests/ -v --tb=short --asyncio-mode=auto

    - name: Run tests with coverage (optional)
      run: |
        pip install pytest-cov
        python -m pytest tests/ --cov=app --cov-report=xml --asyncio-mode=auto

    - name: Upload coverage to Codecov (optional)
      if: success()
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests